name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Validate:
    runs-on: ubuntu-latest
    env:
      image_name: ${{ github.repository }}
      github_owner: ${{ github.repository_owner }}
      github_repo: ${{ github.repository }}
      github_user: ${{ github.actor }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --release --verbose
       
